cmake_minimum_required(VERSION 3.25)
project(SpectralRZ LANGUAGES C CXX)
find_package(AMReX REQUIRED CONFIG)
if(NOT AMReX_SYCL_FOUND)
    message(FATAL_ERROR "This test requires an AMReX SYCL build")
endif()
find_package(MKL REQUIRED CONFIG)
add_executable(test_batched_mkl_fft test_batched_mkl_fft.cpp)
target_compile_features(test_batched_mkl_fft PRIVATE cxx_std_17)
target_include_directories(test_batched_mkl_fft PRIVATE ../../../Source)
target_link_libraries(test_batched_mkl_fft PRIVATE AMReX::amrex MKL::MKL_SYCL::DFT)
enable_testing()
add_test(NAME batched_mkl_fft COMMAND test_batched_mkl_fft amrex.max_gpu_streams=3)
set_tests_properties(batched_mkl_fft PROPERTIES TIMEOUT 30)
