# Copyright 2026 The WarpX Community
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

"""Regenerate the independent Python/Simpson fixtures for the C++ model test."""

from pathlib import Path

import numpy as np
from calibrated_pjg import PARAMETERS, sdcs
from pjg_moments import LossGrid
from reference import free_maximum_transfer


def main():
    def array(values):
        formatted = [f"{value:.17g}" for value in values]
        return (
            "{\n"
            + "\n".join(
                "            " + ", ".join(formatted[i : i + 3]) + ","
                for i in range(0, len(formatted), 3)
            )
            + "\n        }"
        )

    energies = np.array([5e3, 7453.0, 5e4, 1e5, 1e6, 8e8, 1e10])
    rows = []
    for index, target in enumerate(("N2", "O2")):
        moments = LossGrid(target, energies, 4097)(PARAMETERS[target])
        for j, energy in enumerate(energies):
            secondary = np.array(
                [
                    0,
                    2,
                    10,
                    100,
                    0.9 * free_maximum_transfer(energy),
                    1.1 * free_maximum_transfer(energy),
                ]
            )
            values = [
                energy,
                moments.total[j],
                moments.kinetic[j],
                moments.kinetic_second[j],
                moments.binding[j],
                moments.tail_total[j],
            ]
            values[1:] = [value * 1e-4 for value in values[1:]]
            rows.append(
                "    {\n        "
                + str(index)
                + ",\n        "
                + array(values)
                + ",\n        "
                + array(secondary)
                + ",\n        "
                + array(sdcs(target, energy, secondary) * 1e-4)
                + "\n    },"
            )
    text = (
        """/* Copyright 2026 The WarpX Community
 *
 * This file is part of WarpX.
 *
 * License: BSD-3-Clause-LBNL
 *
 * Generated by generate_reference.py from independent Python quadrature.
 * Energies are eV; cross sections are SI, per molecule and unit charge.
 */
#ifndef WARPX_PJG_REFERENCE_DATA_H_
#define WARPX_PJG_REFERENCE_DATA_H_

struct ReferenceRow
{
    int m_target;
    double m_moments[6]; // E, total, kinetic, second, binding, above-free total.
    double m_secondary[6];
    double m_sdcs[6];
};
constexpr ReferenceRow reference_rows[] = {
"""
        + "\n".join(rows)
        + "\n};\n\n#endif // WARPX_PJG_REFERENCE_DATA_H_\n"
    )
    Path(__file__).with_name("PJGReferenceData.H").write_text(text)


if __name__ == "__main__":
    main()
