cmake_minimum_required(VERSION 3.25)
project(PrescribedFluids LANGUAGES C CXX)
find_package(AMReX REQUIRED CONFIG)
if(AMReX_CUDA_FOUND)
    enable_language(CUDA)
    set_source_files_properties(test_profiles.cpp PROPERTIES LANGUAGE CUDA)
elseif(AMReX_HIP_FOUND)
    enable_language(HIP)
    set_source_files_properties(test_profiles.cpp PROPERTIES LANGUAGE HIP)
endif()
add_executable(test_fluid_profiles test_profiles.cpp)
target_compile_features(test_fluid_profiles PRIVATE cxx_std_17)
target_include_directories(test_fluid_profiles PRIVATE ../../../Source)
target_link_libraries(test_fluid_profiles PRIVATE AMReX::amrex)
enable_testing()
add_test(NAME fluid_profiles COMMAND test_fluid_profiles)
set_tests_properties(fluid_profiles PROPERTIES TIMEOUT 30)
