# Copyright 2026 The WarpX Community
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

"""Zero-field heating, cooling and equilibrium with prepared elmolcs data.

No cross sections are generated by this test. Statistical checks complement
the deterministic forward/reverse power integrals in test_elmolcs.py.
"""

import argparse
import time
from pathlib import Path

import numpy as np

from pywarpx import picmi

parser = argparse.ArgumentParser()
parser.add_argument("--data-dir", type=Path, required=True)
parser.add_argument("--particles", type=int, default=65536)
parser.add_argument("--steps", type=int, default=128)
args = parser.parse_args()

grid = picmi.Cartesian1DGrid(
    number_of_cells=[1],
    lower_bound=[0],
    upper_bound=[100],
    lower_boundary_conditions=["periodic"],
    upper_boundary_conditions=["periodic"],
    lower_boundary_conditions_particles=["periodic"],
    upper_boundary_conditions_particles=["periodic"],
    warpx_max_grid_size=1,
    warpx_blocking_factor=1,
)
cases, collisions = [], []
for gas in ["N2", "O2"]:
    directory = (args.data_dir / gas / "IAA").resolve()
    for temperature in [100, 300, 1000]:
        for factor in [0.25, 1, 4]:
            thermal_speed = np.sqrt(
                picmi.constants.kb * temperature * factor / picmi.constants.m_e
            )
            name = f"e_{gas}_{temperature}_{factor}".replace(".", "_")
            electron = picmi.Species(
                particle_type="electron",
                name=name,
                initial_distribution=picmi.UniformDistribution(
                    density=1, rms_velocity=[thermal_speed] * 3
                ),
                warpx_do_not_deposit=True,
                warpx_do_not_gather=True,
            )
            collisions.append(
                picmi.MCCCollisions(
                    name="mcc_" + name,
                    species=electron,
                    # O2 rotational rates are much weaker. Increase exposure
                    # so its heating signal is resolved above sampling noise.
                    background_density=1e29 if gas == "N2" else 4e30,
                    background_temperature=temperature,
                    scattering_processes={
                        "elastic": {
                            "cross_section": str(
                                directory / "thermal_rotation_elastic.txt"
                            ),
                            "rotation_file": str(directory / "thermal_rotation.rot"),
                            "rotation_model": "elastic_dcs",
                            "scattering_angle_model": "IAA",
                            "differential_cross_section": str(
                                directory / "elastic_dcs.txt"
                            ),
                            "rotational_temperature": temperature,
                        }
                    },
                )
            )
            cases.append((electron, temperature, factor))

sim = picmi.Simulation(
    solver=picmi.ElectromagneticSolver(grid=grid, method="Yee", cfl=0.9),
    time_step_size=1e-17,
    max_steps=args.steps,
    warpx_collisions=collisions,
    warpx_random_seed=14653,
    verbose=0,
)
for species, _, _ in cases:
    sim.add_species(
        species,
        layout=picmi.GriddedLayout(
            n_macroparticle_per_cell=[args.particles], grid=grid
        ),
    )
sim.initialize_inputs()
sim.initialize_warpx()


def energies(name):
    u2 = []
    for tile in sim.particles.get(name).iterator(level=0):
        values = []
        for key in ["ux", "uy", "uz"]:
            component = tile[key]
            values.append(
                (
                    component.get()
                    if hasattr(component, "get")
                    else np.asarray(component)
                ).astype(float)
            )
        u2.append(sum(v * v for v in values))
    u2 = np.concatenate(u2)
    return (
        picmi.constants.m_e
        * u2
        / (picmi.constants.q_e * (1 + np.sqrt(1 + u2 / picmi.constants.c**2)))
    )


initial = {s.name: energies(s.name) for s, _, _ in cases}
start = time.perf_counter()
sim.step(args.steps)
sim.particles.get(cases[0][0].name).sum_particle_weight(local=True)
elapsed = time.perf_counter() - start
for species, temperature, factor in cases:
    delta = energies(species.name) - initial[species.name]
    error = np.sqrt(delta.var() / len(delta))
    if factor < 1:
        assert delta.mean() > 3 * error, (species.name, delta.mean(), error)
    elif factor > 1:
        assert delta.mean() < -3 * error, (species.name, delta.mean(), error)
    else:
        assert abs(delta.mean()) < 7 * error, (species.name, delta.mean(), error)
    print(
        species.name, "mean energy change (eV)", delta.mean(), "standard error", error
    )
print("Zero-field thermal tests passed; step seconds:", elapsed)
sim.finalize()
